/**
 * L.7 full-stack test — Advanced Timetable Engine.
 *
 * Builds an isolated scenario and verifies against the live DB:
 *  1. Required lessons per class per subject are all placed (singles + doubles).
 *  2. Double lessons land on consecutive periods (same day) by default.
 *  3. A combination group schedules the subject ONCE at the SAME (day, period)
 *     across all member classes, with the same teacher.
 *  4. SUBJECT_MORNING constraint keeps a subject within the morning periods.
 *  5. TEACHER_TIMEOFF constraint keeps a teacher's lessons out of their off slot.
 *  6. Remaining L.7 rules: STREAM_DISTRIBUTION, DOUBLE_SAME_DAY, CLASS_STREAM_CONFLICT.
 *  7. No class is double-booked; no teacher is double-booked.
 *  8. The Master Button job runs in the background to DONE with progress 100.
 *
 * Cleans up everything it creates and restores existing timetable slots? (We do
 * not touch other tenants; we wipe & regenerate slots for THIS tenant, which the
 * generator does anyway. The seed timetable is regenerated by the normal app, so
 * we only assert on our own isolated classes/subjects.)
 */
import { PrismaClient } from "@prisma/client";
import { runGeneration } from "../src/lib/services/timetable-engine.service";

const db = new PrismaClient();
let pass = 0, fail = 0;
function check(name: string, cond: boolean) {
  if (cond) { pass++; console.log(`  \u2713 ${name}`); }
  else { fail++; console.log(`  \u2717 ${name}`); }
}
function su(u: any, tenantId: string) {
  return { id: u.id, tenantId, neyoLoginId: u.id, fullName: u.fullName, phone: null, email: u.email, role: u.role, secondaryRole: null, language: "en" } as any;
}

async function main() {
  const t = await db.tenant.findUnique({ where: { slug: "karibu-high" } });
  if (!t) throw new Error("tenant not found");
  const tid = t.id;
  const principal = su(await db.user.findFirst({ where: { tenantId: tid, role: "PRINCIPAL" } }), tid);

  // Snapshot existing timetable slots so we can restore them after the test.
  const existingSlots = await db.timetableSlot.findMany({ where: { tenantId: tid } });

  // --- isolated scenario: 2 classes + 2 subjects + 2 teachers ---
  const suffix = Date.now() % 100000;
  const clsA = await db.schoolClass.create({ data: { tenantId: tid, level: `TT${suffix}`, stream: "EAST", curriculum: "8-4-4" } });
  const clsB = await db.schoolClass.create({ data: { tenantId: tid, level: `TT${suffix}`, stream: "WEST", curriculum: "8-4-4" } });
  const math = await db.subject.create({ data: { tenantId: tid, name: "TT-Math", code: `TTM${suffix}`, curriculum: "8-4-4" } });
  const phys = await db.subject.create({ data: { tenantId: tid, name: "TT-Physics", code: `TTP${suffix}`, curriculum: "8-4-4" } });
  const tMath = await db.user.create({ data: { tenantId: tid, neyoLoginId: `ttm${suffix}`, fullName: "TT Math Teacher", role: "TEACHER", isActive: true } as any });
  const tPhys = await db.user.create({ data: { tenantId: tid, neyoLoginId: `ttp${suffix}`, fullName: "TT Phys Teacher", role: "TEACHER", isActive: true } as any });

  // Configs: small day so packing is tight but solvable. lunch shift 1 (period 5).
  for (const c of [clsA, clsB]) {
    await db.timetableConfig.create({ data: { tenantId: tid, classId: c.id, periodsPerDay: 8, freePeriodsPerWeek: 0, coCurricularCount: 0, lunchShift: 1 } });
  }

  // Math: 4 lessons, 1 double (=> 1 double + 2 singles) per class, Math teacher.
  for (const c of [clsA, clsB]) {
    await db.classSubjectNeed.create({ data: { tenantId: tid, classId: c.id, subjectId: math.id, teacherId: tMath.id, lessonsPerWeek: 4, doubleCount: 1 } });
  }

  // English: split double allowed so we can verify DOUBLE_SAME_DAY blocks cross-day splitting.
  const eng = await db.subject.create({ data: { tenantId: tid, name: "TT-English", code: `TTE${suffix}`, curriculum: "8-4-4" } });
  await db.classSubjectNeed.create({ data: { tenantId: tid, classId: clsA.id, subjectId: eng.id, teacherId: tMath.id, lessonsPerWeek: 2, doubleCount: 1, allowSplitDouble: true } });

  // Physics combination group: clsA + clsB combined, 2 lessons, shared Physics teacher.
  const group = await db.combinationGroup.create({ data: { tenantId: tid, name: "TT Physics Combo", subjectId: phys.id, teacherId: tPhys.id, lessonsPerWeek: 2, doubleCount: 0, scope: "SELECTED", source: "MANUAL", active: true } });
  await db.combinationGroupClass.createMany({ data: [
    { tenantId: tid, groupId: group.id, classId: clsA.id },
    { tenantId: tid, groupId: group.id, classId: clsB.id },
  ]});

  // Constraints: Math must be in the morning (<= period 4); Math teacher off Monday P1.
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "SUBJECT_MORNING", label: "Math morning", enabled: true, isHard: true, configJson: JSON.stringify({ subjectIds: [math.id], latestPeriod: 4 }) } });
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "TEACHER_TIMEOFF", label: "Respect time off", enabled: true, isHard: true, configJson: "{}" } });
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "LESSON_DISTRIBUTION", label: "Spread", enabled: true, configJson: "{}" } });
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "DOUBLE_SAME_DAY", label: "Double same day", enabled: true, isHard: true, configJson: "{}" } });
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "STREAM_DISTRIBUTION", label: "Stream distribution", enabled: true, isHard: true, configJson: JSON.stringify({ subjectIds: [math.id], maxSameDayPerLevel: 2 }) } });
  await db.timetableConstraint.create({ data: { tenantId: tid, kind: "CLASS_STREAM_CONFLICT", label: "Class stream conflict", enabled: true, isHard: true, configJson: JSON.stringify({ teacherIds: [tMath.id] }) } });
  await db.teacherTimeOff.create({ data: { tenantId: tid, teacherId: tMath.id, dayOfWeek: 1, period: 1 } });

  const ourClassIds = [clsA.id, clsB.id];

  // Create a job row and run the generation synchronously (await) for deterministic assert.
  const job = await db.timetableGenerationJob.create({ data: { tenantId: tid, status: "QUEUED", phase: "Queued", startedById: principal.id, startedByName: principal.fullName } });
  const result = await runGeneration(tid, job.id, principal);

  try {
    // Re-read the job: must be DONE @ 100.
    const doneJob = await db.timetableGenerationJob.findUnique({ where: { id: job.id } });
    check("Master Button job completes (status DONE, progress 100)", doneJob?.status === "DONE" && doneJob?.progress === 100);

    // Pull only OUR classes' academic slots.
    const slots = await db.timetableSlot.findMany({ where: { tenantId: tid, classId: { in: ourClassIds }, slotType: "ACADEMIC" } });
    const mathSlots = slots.filter((s) => s.subjectId === math.id);
    const physSlots = slots.filter((s) => s.subjectId === phys.id);
    const engSlots = slots.filter((s) => s.subjectId === eng.id);

    // 1) Required lessons placed: Math 4 per class x2 = 8; Physics combo 2 (counted per class => 4 rows)
    check("Math: 4 lessons per class placed (8 total)", mathSlots.length === 8);
    if (mathSlots.length !== 8) console.log("math slots", mathSlots.map((s) => `${s.classId}:${s.dayOfWeek}:${s.period}`).join(", "));
    check("Physics combo: 2 lessons across both classes (4 rows)", physSlots.length === 4);

    // 2) Math double consecutive: for each class, there is a day with 2 consecutive math periods.
    function hasConsecutiveDouble(classId: string) {
      const byDay = new Map<number, number[]>();
      for (const s of mathSlots.filter((x) => x.classId === classId)) {
        const arr = byDay.get(s.dayOfWeek) ?? []; arr.push(s.period); byDay.set(s.dayOfWeek, arr);
      }
      for (const [, periods] of byDay) {
        periods.sort((a, b) => a - b);
        for (let i = 0; i < periods.length - 1; i++) if (periods[i + 1] === periods[i] + 1) return true;
      }
      return false;
    }
    check("Math double lands on consecutive periods (class A)", hasConsecutiveDouble(clsA.id));
    check("Math double lands on consecutive periods (class B)", hasConsecutiveDouble(clsB.id));

    // 3) Combination: both classes share the SAME (day, period) for physics, same teacher.
    const physA = physSlots.filter((s) => s.classId === clsA.id).map((s) => `${s.dayOfWeek}:${s.period}`).sort();
    const physB = physSlots.filter((s) => s.classId === clsB.id).map((s) => `${s.dayOfWeek}:${s.period}`).sort();
    check("Combination scheduled at SAME periods across member classes", physA.length === 2 && JSON.stringify(physA) === JSON.stringify(physB));
    check("Combination uses the shared teacher", physSlots.every((s) => s.teacherId === tPhys.id));

    // 4) Math morning constraint: all math periods <= 4.
    check("SUBJECT_MORNING: all Math lessons in periods 1-4", mathSlots.every((s) => s.period <= 4));

    // 5) Teacher time-off: Math teacher has no lesson Monday period 1.
    const mathTeacherSlots = slots.filter((s) => s.teacherId === tMath.id);
    check("TEACHER_TIMEOFF: Math teacher free on Mon P1", !mathTeacherSlots.some((s) => s.dayOfWeek === 1 && s.period === 1));

    // 6) Remaining L.7 rules.
    const mathADays = new Set(mathSlots.filter((s) => s.classId === clsA.id).map((s) => s.dayOfWeek));
    const mathBDays = new Set(mathSlots.filter((s) => s.classId === clsB.id).map((s) => s.dayOfWeek));
    const sameDayAcrossStreams = [...mathADays].filter((d) => mathBDays.has(d));
    const sameTimeAcrossStreams = mathSlots
      .filter((s) => s.classId === clsA.id)
      .map((s) => `${s.dayOfWeek}:${s.period}`)
      .filter((slot) => mathSlots.filter((x) => x.classId === clsB.id).some((x) => `${x.dayOfWeek}:${x.period}` === slot));
    check("STREAM_DISTRIBUTION: same level streams avoid same-time same-subject bunching", sameTimeAcrossStreams.length === 0);

    const englishByDay = new Map<number, number[]>();
    for (const s of engSlots) {
      const arr = englishByDay.get(s.dayOfWeek) ?? []; arr.push(s.period); englishByDay.set(s.dayOfWeek, arr);
    }
    const englishSameDayDouble = [...englishByDay.values()].some((periods) => periods.length === 2);
    check("DOUBLE_SAME_DAY: split-allowed double still stays on the same day", englishSameDayDouble);

    let streamTeacherConflict = false;
    const tMathBySlot = new Map<string, string[]>();
    for (const s of slots.filter((s) => s.teacherId === tMath.id)) {
      const key = `${s.dayOfWeek}:${s.period}`;
      const arr = tMathBySlot.get(key) ?? []; arr.push(s.classId); tMathBySlot.set(key, arr);
    }
    for (const classIds of tMathBySlot.values()) {
      const levels = classIds.map((cid) => (cid === clsA.id ? clsA.level : cid === clsB.id ? clsB.level : ""));
      if (levels.filter(Boolean).length > 1) streamTeacherConflict = true;
    }
    check("CLASS_STREAM_CONFLICT: shared teacher avoids same-time stream clashes", !streamTeacherConflict);

    // 7) No class double-booking (within our classes) & no teacher double-booking.
    const classKeys = new Set<string>(); let classClash = false;
    for (const s of slots) { const k = `${s.classId}:${s.dayOfWeek}:${s.period}`; if (classKeys.has(k)) classClash = true; classKeys.add(k); }
    check("No class double-booked", !classClash);
    const allSlots = await db.timetableSlot.findMany({ where: { tenantId: tid, teacherId: { in: [tMath.id, tPhys.id] } } });
    const tKeys = new Set<string>(); let tClash = false;
    for (const s of allSlots) {
      // a combination slot legitimately occupies one teacher across 2 classes at the same period:
      // count distinct (teacher, day, period); if the same teacher has two DIFFERENT subjects at the same time => clash.
      const k = `${s.teacherId}:${s.dayOfWeek}:${s.period}:${s.subjectId}`;
      const tp = `${s.teacherId}:${s.dayOfWeek}:${s.period}`;
      if (tKeys.has(tp) && !tKeys.has(k)) tClash = true;
      tKeys.add(tp); tKeys.add(k);
    }
    check("No teacher double-booked (combination counts as one lesson)", !tClash);

    const ourUnplaced = result.unplaced.filter((u) => u.classLabel.includes(`TT${suffix}`) || u.subjectCode.includes(`${suffix}`));
    check("Generation reported no unplaced loads for our scenario", ourUnplaced.length === 0);
    if (ourUnplaced.length) console.log("unplaced", JSON.stringify(ourUnplaced, null, 2));
  } finally {
    // cleanup our scenario
    await db.timetableSlot.deleteMany({ where: { tenantId: tid, classId: { in: ourClassIds } } }).catch(() => {});
    await db.timetableGenerationJob.delete({ where: { id: job.id } }).catch(() => {});
    await db.teacherTimeOff.deleteMany({ where: { teacherId: tMath.id } }).catch(() => {});
    await db.timetableConstraint.deleteMany({ where: { tenantId: tid, label: { in: ["Math morning", "Respect time off", "Spread", "Double same day", "Stream distribution", "Class stream conflict"] } } }).catch(() => {});
    await db.combinationGroupClass.deleteMany({ where: { groupId: group.id } }).catch(() => {});
    await db.combinationGroup.delete({ where: { id: group.id } }).catch(() => {});
    await db.classSubjectNeed.deleteMany({ where: { classId: { in: ourClassIds } } }).catch(() => {});
    await db.timetableConfig.deleteMany({ where: { classId: { in: ourClassIds } } }).catch(() => {});
    await db.user.deleteMany({ where: { id: { in: [tMath.id, tPhys.id] } } }).catch(() => {});
    await db.subject.deleteMany({ where: { id: { in: [math.id, phys.id, eng.id] } } }).catch(() => {});
    await db.schoolClass.deleteMany({ where: { id: { in: ourClassIds } } }).catch(() => {});
    // restore the pre-test timetable slots (generation wiped all tenant slots)
    await db.timetableSlot.deleteMany({ where: { tenantId: tid } }).catch(() => {});
    if (existingSlots.length > 0) {
      await db.timetableSlot.createMany({ data: existingSlots.map(({ id, ...rest }) => rest) }).catch(() => {});
    }
  }

  console.log(`\n  ${pass} passed, ${fail} failed`);
  if (fail === 0) console.log("  \u2705 L.7 timetable engine all green");
  await db.$disconnect();
  if (fail > 0) process.exit(1);
}

main().catch(async (e) => { console.error(e); await db.$disconnect(); process.exit(1); });
